# This workflow will do a clean install of the dependencies and run tests
# across different versions
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - scripts/ci-check
# - scripts/ci

---
name: purescript / main

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use PureScript compiler and toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.13.8"

      - name: Install project dependencies
        run: echo "<install dependencies>"

      - name: Run exercism/purescript ci pre-check (checks config, lint code) for all exercises
        run: echo "scripts/ci-check"

  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [0.13.8]

    steps:
      - uses: actions/checkout@v2

      - name: Use PureScript compiler ${{ matrix.version }}
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: ${{ matrix.version }}

      - name: Install project dependencies
        run: echo "<install dependencies>"

      - name: Cache local .spago directories
        uses: actions/cache@v2
        with:
          path: build/*/.spago
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}

      - name: Cache build directories
        uses: actions/cache@v2
        with:
          path: build/*/build
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}

      - name: Run exercism/purescript ci (runs tests) for all exercises
        run: ./bin/test-all-exercises.sh ./exercises
